kind: ImageSetConfiguration
apiVersion: mirror.openshift.io/v2alpha1
mirror:
  platform:
    channels:
    - name: stable-4.19 
      minVersion: 4.19.0
      maxVersion: 4.19.0
    graph: true 
  operators:
    - catalog: registry.redhat.io/redhat/redhat-operator-index:v4.19
    - catalog: registry.redhat.io/redhat/certified-operator-index:v4.19
