apiVersion: k8s.cni.cncf.io/v1
kind: NetworkAttachmentDefinition
metadata:
  name: ovs-br-ex-nad
  namespace: tslocprj
spec:
  config: '{
    "cniVersion": "0.3.1",
    "name": "ovs-br-ex-network",
    "type": "ovs",
    "bridge": "br-ex",
    "ipam": {}
  }'
