apiVersion: nmstate.io/v1
kind: NodeNetworkConfigurationPolicy
metadata:
  name: vlan100-bridge-policy-node-1
spec:
  nodeSelector:
    kubernetes.io/hostname: tslosvmw1.corp.dcaddevsso.com
  desiredState:
    interfaces:
    # Create VLAN interface
    - name: ens1f2.100  # Format: physical-interface.vlan-id
      type: vlan
      state: up
      vlan:
        base-iface: ens1f2  # Your physical interface
        id: 100             # VLAN ID
      ipv4:
        enabled: false      # No IP on VLAN interface itself
        dhcp: false
    
    # Create Linux bridge attached to VLAN
    - name: br-vlan100
      type: linux-bridge
      state: up
      ipv4:
        enabled: false
        dhcp: false
      bridge:
        options:
          stp:
            enabled: false
        port:
        - name: ens1f2.100  # Attach VLAN interface to bridge

---

apiVersion: nmstate.io/v1
kind: NodeNetworkConfigurationPolicy
metadata:
  name: vlan100-bridge-policy-node-2
spec:
  nodeSelector:
    kubernetes.io/hostname: tslosvmw2.corp.dcaddevsso.com
  desiredState:
    interfaces:
    # Create VLAN interface
    - name: ens1f3.100  # Format: physical-interface.vlan-id
      type: vlan
      state: up
      vlan:
        base-iface: ens1f3  # Your physical interface
        id: 100             # VLAN ID
      ipv4:
        enabled: false      # No IP on VLAN interface itself
        dhcp: false
    
    # Create Linux bridge attached to VLAN
    - name: br-vlan100
      type: linux-bridge
      state: up
      ipv4:
        enabled: false
        dhcp: false
      bridge:
        options:
          stp:
            enabled: false
        port:
        - name: ens1f3.100  # Attach VLAN interface to bridge

---

apiVersion: nmstate.io/v1
kind: NodeNetworkConfigurationPolicy
metadata:
  name: vlan100-bridge-policy-node-3
spec:
  nodeSelector:
    kubernetes.io/hostname: tslosvmw3.corp.dcaddevsso.com
  desiredState:
    interfaces:
    # Create VLAN interface
    - name: ens1f3.100  # Format: physical-interface.vlan-id
      type: vlan
      state: up
      vlan:
        base-iface: ens1f3  # Your physical interface
        id: 100             # VLAN ID
      ipv4:
        enabled: false      # No IP on VLAN interface itself
        dhcp: false
    
    # Create Linux bridge attached to VLAN
    - name: br-vlan100
      type: linux-bridge
      state: up
      ipv4:
        enabled: false
        dhcp: false
      bridge:
        options:
          stp:
            enabled: false
        port:
        - name: ens1f3.100  # Attach VLAN interface to bridge
